CREATE OR REPLACE TRIGGER TRG_CREDIT 
BEFORE INSERT OR UPDATE OF CREDIT ON CUSTOMER 
REFERENCING OLD AS ALT NEW AS NEU 
FOR EACH ROW DECLARE
BEGIN
  IF(:NEU.CREDIT < 0) THEN
  RAISE_APPLICATION_ERROR(-20123, 'Kredit kann nicht unter 0 sein, uebernommener Kredit: ' || :NEU.CREDIT || '.');
  END IF;
END;